spring.application.name=open-feed
spring.mvc.servlet.path=/api/v1/

spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.zytmogaxwhipuvmztxjc
#Credenciais críticas do sistema nunca devem estar disponíveis no código fonte
spring.datasource.password=Senhor_Cafe101
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true