-- Baseline migration: documents the schema as produced by Hibernate's
-- ddl-auto=update (inferred from the JPA entities), so a fresh/empty
-- database can be bootstrapped the same way the existing Supabase
-- database already looks. On the existing production database this
-- migration is never executed — it is recorded via Flyway baselining
-- (see spring.flyway.baseline-on-migrate / baseline-version).

CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    email    VARCHAR(255) NOT NULL UNIQUE,
    senha    VARCHAR(255) NOT NULL
);

CREATE TABLE post (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo         VARCHAR(255),
    conteudo       VARCHAR(255),
    data_postagem  TIMESTAMP,
    tag            VARCHAR(255),
    user_id        BIGINT REFERENCES users (id)
);

CREATE TABLE comment (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conteudo         VARCHAR(255),
    data_comentario  TIMESTAMP,
    user_id          BIGINT REFERENCES users (id),
    post_id          BIGINT REFERENCES post (id) ON DELETE CASCADE
);

CREATE TABLE post_like (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT REFERENCES users (id),
    post_id       BIGINT REFERENCES post (id) ON DELETE CASCADE,
    data_curtida  TIMESTAMP,
    UNIQUE (user_id, post_id)
);

CREATE TABLE comment_like (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT REFERENCES users (id),
    comment_id    BIGINT REFERENCES comment (id) ON DELETE CASCADE,
    data_curtida  TIMESTAMP,
    UNIQUE (user_id, comment_id)
);
